name: iRestore
main: com.github.triarry.iRestore.iRestore
version: 1.12.2
author: triarry
softdepend: [Vault, MyPet]
commands:
    irestore:
        description: Tells the player information about this plugin.
        usage: /<command>
permissions:
    irestore.participate:
        description: Required for players to actively participate in features of the plugin.
    irestore.update:
        description: Tells the player if an update is available.
        default: false
    irestore.keep.all:
        description: Allows the player to keep all their items, armor and XP.
        children:
            irestore.keep.xp: true
            irestore.keep.inventory: true
    irestore.keep.xp:
        description: Allows the player to keep their XP.
    irestore.keep.inventory:
        description: Allows the player to keep all their items and armor.
    irestore.money.steal:
        description: Allows a player to steal another players money
    irestore.money.exempt:
        description: Overrides another player's ability to steal your money
        default: false
    irestore.events.other.all:
        description: Allows a player's inventory to be saved by all "other" events.
        default: false
        children:
            irestore.events.other.anvil: true
            irestore.events.other.cactus: true
            irestore.events.other.drowning: true
            irestore.events.other.enderpearl: true
            irestore.events.other.falling: true
            irestore.events.other.fire: true
            irestore.events.other.lava: true
            irestore.events.other.lightning: true
            irestore.events.other.magic: true
            irestore.events.other.starvation: true
            irestore.events.other.suffocation: true
            irestore.events.other.suicide: true
            irestore.events.other.tnt: true
            irestore.events.other.void: true
    irestore.events.other.anvil:
        description: Allows a player's inventory to be saved after being killed by an anvil
    irestore.events.other.cactus:
        description: Allows a player's inventory to be saved after being killed by a cactus
    irestore.events.other.drowning:
        description: Allows a player's inventory to be saved after being killed via drowning
    irestore.events.other.enderpearl:
        description: Allows a player's inventory to be saved after being killed by enderpearl falling damage
    irestore.events.other.falling:
        description: Allows a player's inventory to be saved after being killed by falling damage
    irestore.events.other.fire:
        description: Allows a player's inventory to be saved after being killed by fire
    irestore.events.other.lava:
        description: Allows a player's inventory to be saved after being killed by lava
    irestore.events.other.lightning:
        description: Allows a player's inventory to be saved after being killed by lightning
    irestore.events.other.magic:
        description: Allows a player's inventory to be saved after being killed by "magic"
    irestore.events.other.starvation:
        description: Allows a player's inventory to be saved after being killed by starving
    irestore.events.other.suffocation:
        description: Allows a player's inventory to be saved after being killed by suffocating in a block
    irestore.events.other.suicide:
        description: Allows a player's inventory to be saved after suiciding
    irestore.events.other.tnt:
        description: Allows a player's inventory to be saved after being killed by TNT
    irestore.events.other.void:
        description: Allows a player's inventory to be saved after being killed by the void
    irestore.events.mobs.all:
        description: Allows a player's inventory to be saved by all mob related events
        default: false
        children:
            irestore.events.mobs.angry_wolf: true
            irestore.events.mobs.baby_zombie: true
            irestore.events.mobs.blaze: true
            irestore.events.mobs.cave_spider: true
            irestore.events.mobs.creeper: true
            irestore.events.elder_guardian: true
            irestore.events.mobs.enderdragon: true
            irestore.events.mobs.enderman: true
            irestore.events.mobs.endermite: true
            irestore.events.mobs.ghast: true
            irestore.events.mobs.giant: true
            irestore.events.mobs.guardian: true
            irestore.events.mobs.iron_golem: true
            irestore.events.mobs.killer_rabbit: true
            irestore.events.mobs.magma_cube: true
            irestore.events.mobs.silverfish: true
            irestore.events.mobs.skeleton: true
            irestore.events.mobs.slime: true
            irestore.events.mobs.spider: true
            irestore.events.mobs.witch: true
            irestore.events.mobs.wither: true
            irestore.events.mobs.wither_skeleton: true
            irestore.events.mobs.zombie: true
            irestore.events.mobs.zombie_pigman: true
            irestore.events.mobs.zombie_villager: true
    irestore.events.mobs.angry_wolf:
        description: Allows a player's inventory to be saved after being killed by an angry wolf
    irestore.events.mobs.baby_zombie:
        description: Allows a player's inventory to be saved after being killed by a baby zombie
    irestore.events.mobs.blaze:
        description: Allows a player's inventory to be saved after being killed by a blaze
    irestore.events.mobs.cave_spider:
        description: Allows a player's inventory to be saved after being killed by a cave spider
    irestore.events.mobs.creeper:
        description: Allows a player's inventory to be saved after being killed by a creeper
    irestore.events.mobs.elder_guardian:
        description: Allows a player's inventory to be saved after begin killed by an elder guardian
    irestore.events.mobs.enderdragon:
        description: Allows a player's inventory to be saved after being killed by an enderdragon
    irestore.events.mobs.enderman:
        description: Allows a player's inventory to be saved after being killed by an enderman
    irestore.events.mobs.ghast:
        description: Allows a player's inventory to be saved after being killed by a ghast
    irestore.events.mobs.giant:
        description: Allows a player's inventory to be saved after being killed by a giant
    irestore.events.mobs.guardian:
        description: Allows a player's inventory to be saved after being killed by a guardian
    irestore.events.mobs.iron_golem:
        description: Allows a player's inventory to be saved after being killed by an iron golem
    irestore.events.mobs.magma_cube:
        description: Allows a player's inventory to be saved after being killed by a magma cube
    irestore.events.mobs.silverfish:
        description: Allows a player's inventory to be saved after being killed by a silverfish
    irestore.events.mobs.skeleton:
        description: Allows a player's inventory to be saved after being killed by a skeleton
    irestore.events.mobs.slime:
        description: Allows a player's inventory to be saved after being killed by a slime
    irestore.events.mobs.spider:
        description: Allows a player's inventory to be saved after being killed by a spider
    irestore.events.mobs.witch:
        description: Allows a player's inventory to be saved after being killed by a witch
    irestore.events.mobs.wither:
        description: Allows a player's inventory to be saved after being killed by a wither
    irestore.events.mobs.wither_skeleton:
        description: Allows a player's inventory to be saved after being killed by a wither skeleton
    irestore.events.mobs.zombie:
        description: Allows a player's inventory to be saved after being killed by a zombie
    irestore.events.mobs.zombie_pigman:
        description: Allows a player's inventory to be saved after being killed by a zombie pigman
    irestore.events.mobs.zombie_villager:
        description: Allows a player's inventory to be saved after being killed by a zombie villager
    irestore.events.pvp.all:
        description: Allows a player's inventory to be saved by all "pvp related" events.
        default: false
        children:
            irestore.events.pvp.bows: true
            irestore.events.pvp.melee: true
            irestore.events.pvp.mypet: true
            irestore.events.pvp.potions: true
            irestore.events.pvp.tamed_wolf: true
            irestore.events.pvp.tnt: true
    irestore.events.pvp.bows:
        description: Allows a player's inventory to be saved after getting killed by another player's bow
    irestore.events.pvp.melee:
        description: Allows a player's inventory to be saved after getting killed by another player's melee weapon
    irestore.events.pvp.mypet:
        description: Allows a player's inventory to be saved after getting killed by another player's MyPet
    irestore.events.pvp.potions:
        description: Allows a player's inventory to be saved after getting killed by another player's potions
    irestore.events.pvp.tamed_wolf:
        description: Allows a player's inventory to be saved after getting killed by another player's wolf
    irestore.events.pvp.tnt:
        description: Allows a player's inventory to be saved after being killed by TNT
